name: build-release

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: bump version and push tag (dry run)
        id: tag_version_dry_run
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true

      - name: build
        run: |
          zip -r "vector-buildpack-cflinuxfs4-v${{ steps.tag_version_dry_run.outputs.new_version }}.zip" .

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: v

      - name: publish-candidate
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.tag_version.outputs.new_tag }}
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          files: |
            vector-buildpack-cflinuxfs4-v${{ steps.tag_version_dry_run.outputs.new_version }}.zip

      - name: delete-rc-releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0
          delete_tag_pattern: rc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: delete-rc-tags
        run: |
          git push --delete origin $(git tag -l '*-rc*') || echo "no rc tags to delete"
