name: test

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test
        uses: sudo-bot/action-shunit2@latest
        with:
          cli: "${GITHUB_WORKSPACE}/test/test.sh"

