name: test

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install JQ Tool
        uses: mbround18/install-jq@v1

      - name: test
        uses: sudo-bot/action-shunit2@latest
        with:
          cli: "./test/test.sh"

