name: test

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup jq
        uses: dcarbone/install-jq-action@v1.0.1
        with:
          version: 1.6

      - name: 'Check jq'
        run: |
          which jq
          jq --version

      - name: test
        uses: sudo-bot/action-shunit2@latest
        with:
          cli: "./test/test.sh"

